FROM node:12-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm install pm2 -g

EXPOSE 8080

CMD [ "pm2-runtime", "npm", "--", "start" ]


# we need mysql database for this app and that mysql user should access any remote system not only localhost 
